### ISSUE TITLE
Generate command not work due to vanilla datapack path change.

### ISSUE THREAD

**Issue by WMGameLive** [mrfdev/advanced-achievements#16]
### 🎆 Advanced Achievements version

7.0.0

### 🖥 Server version

1.21.1

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

In the new Minecraft version, the directory path for advancements in datapacks has changed. The folder name should now be "advancement", but the generate command still uses "advancements", this causes Minecraft to be unable to read these advancements.

### 📄 Server logs

```

```

### ⚙ Configuration

```

```

**Comment by Greymagic27** [comment]
Thanks for the issue.

Do you happen to know where in the code this is declared? If so I can make that change.

Otherwise it falls under #11 with me not having enough knowledge about the plugin code to fix the issue

**Comment by WMGameLive** [comment]
> Thanks for the issue.
> 
> Do you happen to know where in the code this is declared? If so I can make that change.
> 
> Otherwise it falls under #11 with me not having enough knowledge about the plugin code to fix the issue

I've looked into it but found nothing. There is no datapack path in the code, it simply creates a JSON data structure and sends it to Bukkit, so maybe it is bukkit/spigot bug? idk.

**Comment by Greymagic27** [comment]
Can you update the issue description where it says 'server logs' to include the error when you run the command?

**Comment by WMGameLive** [comment]
> Can you update the issue description where it says 'server logs' to include the error when you run the command?

There is no any errors, just datapack folder name is wrong so minecraft will not load it.

**Comment by WMGameLive** [comment]
> So the command just doesn't give any output/action ? I would've thought it'd spit out an error.. hm. Makes it harder to diagnose then

I recorded a video, to make sure you understand what I mean.
https://youtu.be/dyiJRn4tT1I

**Comment by Greymagic27** [comment]
Thanks.

Looked into the issue but still can't see how to solve it sadly

**Comment by mrfloris** [comment]
hm, i don't quite understand, because the database is a sub dir called advancedachievemnets, with a sub dir, that sub dir is not vanilla .. so I dunno. i can't really find any code related to this, am I overlooking it that much?

**Comment by WMGameLive** [comment]
I think this is bukkit/spigot bug maybe? This plugin just create advancement data and send it to bukkit by using Bukkit.loadAdvancement(), I can't find any code about datapack, or maybe it's just because I suck.
